# Generated by Django 5.2.7 on 2025-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chronometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('state', models.PositiveIntegerField()),
                ('elapsed_time', models.FloatField()),
            ],
        ),
    ]
