# Generated by Django 5.2.7 on 2025-10-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcontroller_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('candle_length', models.FloatField()),
                ('elapsed_time', models.FloatField()),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ImuLedArray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('imu_angle', models.FloatField()),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('note', models.CharField(max_length=7)),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RemoteControlledCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('velocity', models.FloatField()),
                ('linear_input', models.FloatField()),
                ('angular_input', models.FloatField()),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Smarthouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('temperature', models.CharField()),
                ('motion_detected', models.BooleanField()),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SolarTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('servo_angle', models.FloatField()),
                ('light_intensity', models.FloatField()),
                ('timestamp', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='chronometer',
            name='timestamp',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
