# Generated by Django 5.2.7 on 2025-10-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcontroller_data', '0002_candlelength_imuledarray_piano_remotecontrolledcar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDevices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_address', models.CharField(max_length=17)),
                ('device_name', models.CharField(max_length=32)),
            ],
        ),
    ]
