# Generated by Django 5.2.7 on 2025-10-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microcontroller_data', '0003_registereddevices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereddevices',
            old_name='max_address',
            new_name='mac_address',
        ),
    ]
