# Generated by Django 5.2.7 on 2025-11-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcontroller_data', '0004_rename_max_address_registereddevices_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candlelength',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imuledarray',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='piano',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='remotecontrolledcar',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='smarthouse',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solartracker',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
