# Generated by Django 5.2.7 on 2025-11-04 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcontroller_data', '0005_alter_candlelength_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronometer',
            name='elapsed_time',
        ),
        migrations.RemoveField(
            model_name='chronometer',
            name='state',
        ),
        migrations.AddField(
            model_name='chronometer',
            name='message',
            field=models.CharField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piano',
            name='note',
            field=models.CharField(max_length=1),
        ),
    ]
